# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script rogers1 and rogers2&2 rogers3 rogers4 rogers5&567'

- script: |
    echo Add other tasks to build, test, and deploy your project then make it exit.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
